### ISSUE TITLE
The Iconography  link in the README is wrong

### ISSUE THREAD

**Issue by mberthouzoz** [brightlayer-ui/icons#177]
#### Describe the bug
The _Iconography_ link is wrong.

#### What is the expected behavior?
The  _Iconography_ link must display the  _Iconography_ page.

#### What are the steps to reproduce?
1. Go to the README.md: [https://github.com/pxblue/icons](https://github.com/pxblue/icons)
2. Click on [Iconography](https://brightlayer-ui.github.io/style/iconography) link

#### Screenshots or links to minimum reproduction example
[https://brightlayer-ui.github.io/style/iconography](https://brightlayer-ui.github.io/style/iconography)

![image](https://user-images.githubusercontent.com/3798675/146000349-d92215d7-44cc-4ae5-a12b-27f3aec0ab4a.png)

**Comment by mberthouzoz** [comment]
The issue with this link: https://github.com/brightlayer-ui/icons/blob/master/design/README.md

Please read the instructions in the [Design ](https://github.com/brightlayer-ui/icons/blob/master/design/README.md) folder before creating or submitting new icons.

**Comment by daileytj** [comment]
@mberthouzoz We are currently in the process of a branding overhaul which will cause some temporary linking issues. We will have this fixed shortly, but in the meantime, you can access the files you are looking for by replacing `brightlayer-ui` with `pxblue` in the url.

**Comment by emclaug2** [comment]
This issue can be closed in the coming week, after the migration is complete.

**Comment by ektasawant** [comment]
Closing this issue, after migration links are working fine.
