### ISSUE TITLE
RN Vector icons package having issues with newer gradle versions

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/icons#211]
#### Describe the bug
When running a CLI project in a newer environment (updated gradle or newer version of RN), it throws an error about some of the items in the build.gradle file.

#### What is the expected behavior?
Should run correctly without error.

#### What are the steps to reproduce?
This is kind of hard to reproduce definitively, but I have heard of it in two cases.

1. BLI team reported seeing this issue when going through their upgrade process from RN 64 to 67
2. I have seen this when starting a new project with the CLI and updating my gradle/gradle plugin versions (not exactly sure what step is the one that causes the issue).

#### Anything else to add?
It seems that replacing our build.gradle file with the newest one from [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons/blob/master/android/build.gradle) makes this issue go away, but we will need to do some testing around compatibility (will probably be a major version change).

**Comment by bkarambe** [comment]
Issue still exists:
<img width="813" alt="Screenshot 2022-11-30 at 11 25 07 AM" src="https://user-images.githubusercontent.com/25982779/204751442-437f68f4-92d5-4b49-a168-4a75a372ba00.png">

**Comment by bkarambe** [comment]
Closing this, as upgrading to RN 70 fixed this issue.
