### ISSUE TITLE
Add Outlet Icons

### ISSUE THREAD

**Issue by JeanMeche** [brightlayer-ui/icons#229]
Would it be possible to add the following outlet icons to the set : 

C14, C19, C39 and their cross-off counter parts ? 

Thx !

**Comment by huayunh** [comment]
These following icons have already been published to all our icon-related packages, under the following names:

Outlet C19, Outlet C14, Outlet C39, Outlet Alt, Outlet C19 Off, Outlet C14 Off, Outlet C39 Off and Outlet Alt Off 

Our website is old (still on React 17 and MUI 4; we have a story to work on it this quarter), so it is not showing all the Brightlayer UI and Material Design icons. Sorry for the confusion.

**Comment by JeanMeche** [comment]
Thanks, I found what I was looking for
