### ISSUE TITLE
Cannot resize icons when using matIconRegistry

### ISSUE THREAD

**Issue by joebochill** [brightlayer-ui/icons#27]
#### Bug or feature request?
Bug

#### What is the expected behavior?
You should be able to resize the <mat-icon> by setting the font-size property in css

#### What is the current behavior?
Icon does not get resized because the viewbox property is removed when the svg is registered.

#### What is your environment?

 Framework
- [x] Angular
- [ ] React
		
#### Anything else to add?
There is an upstream bug for this: https://github.com/angular/material2/issues/5488

**Comment by joebochill** [comment]
No movement on this from the Angular Material team as of yet. There is a proposed solution that fixes it which has not yet been merged into the trunk. There is also a workaround provided in the comment thread, but it needs to be added to the product team's code, not our library.

**Comment by huayunh** [comment]
Currently none of our demos in monorepo is using icon registry 
Need to re-investigate on this

**Comment by daileytj** [comment]
Look into what works and doesn't work to see if this needs to be kept open. If we're not going to fix this, close it.
